replicaCount: 1

image:
  repository: mikigbo/test-server
  tag: "0.0.4"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: "/metrics"
  prometheus.io/port: "3000"

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: test-server.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

secret:
  name: test-server-secret
  data: {}

config:
  setting1: "value1"
  setting2: "value2"
