apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: {{ .Release.Name }}-test-server
data:
  {{- range $key, $value := .Values.configMap.envVars }}
  {{ $key }}: {{ quote $value }}
  {{- end }}

