apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    job: {{ .Release.Name }}
    app: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      name: {{ .Values.service.portName }}
      protocol: TCP
  selector:
    app: {{ .Release.Name }}
